create table QUESTION
(
	ID INTEGER default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EF1C2AD5_4293_4285_99DC_378B52563A3D) auto_increment,
	TITLE VARCHAR(50),
	DESCRIPTION CLOB,
	GMT_CREATE BIGINT,
	GMT_MOTIFIED BIGINT,
	CREATOR INTEGER,
	COMMENT_COUNT INTEGER default 0,
	VIEW_COUNT INTEGER default 0,
	LIKE_COUNT INTEGER default 0,
	TAG VARCHAR(256),
	constraint QUESTION_PK
		primary key (ID)
);